### ISSUE TITLE
Consider adding non-normative guidance on when not to use EAT/UCCS media types

### ISSUE THREAD

**Issue by gmandyam** [thomas-fossati/draft-eat-mt#17]
It may be desirable to use an alternative media type (e.g. the existing CBOR and CWT media types) for attestation payloads under certain conditions.  For instance, middleboxes that can peek into traffic flows (which  exist  even for certain types of TLS connections) may drop or modify attestation tokens.  In such cases, it might be useful to obscure the token by simply identifying it as a JWT/CWT/CBOR/JSON media type.  Obviously making use of an obfuscating (but still valid) media type is not sufficient to protect against all peeking/modifying proxies, but this could be one of multiple countermeasures available to implementers.

Moreover, filtering middleboxes may drop unknown media types - and the media types defined in this document would likely be unknown to existing implementations.  As far as I can tell, such kinds of blocking policies are consistent with what is described inhttps://datatracker.ietf.org/doc/html/rfc7754.

Such a discussion of when it might be appropriate not to use the media types defined in this document could be in the security considerations section.  If this is deemed to be desirable, I can put together a candidate PR.

**Comment by thomas-fossati** [comment]
I am not an expert in web filtering, but I'd imagine it applies to URLs and web origins, rather than media types.  I.e., to content identification parameters rather than protocol elements that control the presentation of said content.

I expect these new media types to be used in REST APIs that are carried over HTTPS, therefore inaccessible to on-path, passive middleboxes.

With an active middlebox that breaks the end-to-end security, all bets are off in terms of what it can do with the payloads, e.g., deep packet inspection, including MIME-type sniffing.

In any case, if you want to put forward some text, please go ahead!

**Comment by gmandyam** [comment]
Closing - won't fix
